 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();

if (!process.env.DISABLE_XORIGIN) {
  app.use(function(req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });
  
app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })
app.route('/api/whoami')
    .get(function(req, res) {
      var ip =       req.headers['x-forwarded-for'].match(/^[^,]+/)[0];    
      var language = req.headers['accept-language'];
      var software = req.headers['user-agent'];
      
      var retval = {
        'ipaddress': ip,
        'language': language,
        'software': software
      }
      res.end(JSON.stringify(retval));//"Browser info here: " + req.headers['x-forwarded-for'].match(/^\d+.\d+.\d+.\d+/))
      
})
app.route('/api/whoami-short')
    .get(function(req, res) {
      var language = req.headers['accept-language'].match(/^[^,;]+/)[0];
      var software = req.headers['user-agent'].match(/\([^)]*\)/)[0];
      software = software.substring(1, software.length - 1);
      var ip =       req.headers['x-forwarded-for'].match(/^[^,]+/)[0];
      var retval = {
        'language': language,
        'software': software,
        'ipaddress': ip
      }
      res.end(JSON.stringify(retval));//"Browser info here: " + req.headers['x-forwarded-for'].match(/^\d+.\d+.\d+.\d+/))
      
})
app.route('/api/whoami-full')
    .get(function(req,res) {
      var language = req.headers['accept-language'];
      var software = req.headers['user-agent'];
      var ip =       req.headers['x-forwarded-for'];
      var retval = {
        'accept-language': language,
        'user-agent': software,
        'x-forwarded-for': ip
      }
      res.end(JSON.stringify(retval));
})
// Respond not found to all the wrong routes
app.use(function(req, res, next){
  res.status(404);
  res.type('txt').send('Not found');
});

// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});